### ISSUE TITLE
JSON interface

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/psi4#1]
## Description
Bakes json read/run capabilities into Psi4 proper which is the primary requirement to use the "psimagic" demonstration as shown at the Psi4 workshop this weekend. This is not ready to go as I would like a few interested parties to discuss the JSON interface, but here for visibility. Full docs and example can be found [here](https://github.com/dgasmith/psi4/blob/json/psi4/driver/json_wrapper.py#L52). A command line run would look like `psi4 --json data.json` which would read in `data.json`, run the requested computation, and dump the result back to `data.json`.

## Features
- [x] Adds Matrix/Vector serialization.
- [x] Adds JSON "input"/output capabilities
- [x] Adds the ability to run JSON "input" files from the command line. 

## TODO
- [ ] Circulate the interface around to see if anything obvious (and simple) is missing.

## Status
- [ ]  Ready to go
